// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoreFootball.Data;

#nullable disable

namespace RestoreFootball.Migrations
{
    [DbContext(typeof(RestoreFootballContext))]
    [Migration("20230613200243_tweaks")]
    partial class tweaks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoreFootball.Models.Gameweek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GreenScore")
                        .HasColumnType("int");

                    b.Property<int?>("NonBibsScore")
                        .HasColumnType("int");

                    b.Property<int?>("OrangeScore")
                        .HasColumnType("int");

                    b.Property<int?>("YellowScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gameweek");
                });

            modelBuilder.Entity("RestoreFootball.Models.GameweekPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameweekId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameweekId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GameweekPlayer");
                });

            modelBuilder.Entity("RestoreFootball.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<bool>("SignedUp")
                        .HasColumnType("bit");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("RestoreFootball.Models.GameweekPlayer", b =>
                {
                    b.HasOne("RestoreFootball.Models.Gameweek", "Gameweek")
                        .WithMany("GameweekPlayers")
                        .HasForeignKey("GameweekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestoreFootball.Models.Player", "Player")
                        .WithMany("GameweekPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gameweek");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RestoreFootball.Models.Gameweek", b =>
                {
                    b.Navigation("GameweekPlayers");
                });

            modelBuilder.Entity("RestoreFootball.Models.Player", b =>
                {
                    b.Navigation("GameweekPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
